/*
* CompanyMapper.java
* @author ICL
* @date 2018-10-31 23:29:21
*/
package com.hwitec.core.dao;

import com.hwitec.core.domain.Company;
import org.common.dao.CurdDao;

public interface CompanyMapper extends CurdDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company 公司表  
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int deleteByPrimaryKey(String companyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company 公司表  
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company 公司表  
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company 公司表  
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    Company selectByPrimaryKey(String companyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company 公司表  
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company 公司表  
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int updateByPrimaryKey(Company record);
}