/*
* LogMapper.java
* @author ICL
* @date 2018-10-31 23:29:21
*/
package com.hwitec.core.dao;

import com.hwitec.core.domain.Log;
import com.hwitec.core.domain.LogWithBLOBs;
import org.common.dao.CurdDao;

public interface LogMapper extends CurdDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log 操作日志表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log 操作日志表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int insert(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log 操作日志表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int insertSelective(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log 操作日志表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    LogWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log 操作日志表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int updateByPrimaryKeySelective(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log 操作日志表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int updateByPrimaryKeyWithBLOBs(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log 操作日志表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int updateByPrimaryKey(Log record);
}