/*
* ModuleMapper.java
* @author ICL
* @date 2018-10-31 23:29:21
*/
package com.hwitec.core.dao;

import com.hwitec.core.domain.Module;
import org.common.dao.CurdDao;

public interface ModuleMapper extends CurdDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module 模块表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int deleteByPrimaryKey(String moduleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module 模块表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module 模块表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module 模块表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    Module selectByPrimaryKey(String moduleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module 模块表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module 模块表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    int updateByPrimaryKey(Module record);
}