/*
* Company.java
* @author ICL
* @date 2018-10-31 23:29:21
*/
package com.hwitec.core.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.common.domain.DataEntity;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_company
 *
 * @mbg.generated 2018-10-31 23:29:21
 */
import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 公司表  
 * 实体类对应的数据表为:sys_company
 * @author ICL
 * @date 2018-10-31 23:29:21
 */
@ApiModel(value ="Company")
public class Company extends DataEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.company_code
     * @Fields companyCode 公司编码
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "公司编码")
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.parent_code
     * @Fields parentCode 父级编号
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "父级编号")
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.parent_codes
     * @Fields parentCodes 所有父级编号
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "所有父级编号")
    private String parentCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.tree_sort
     * @Fields treeSort 本级排序号（升序）
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "本级排序号（升序）")
    private Long treeSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.tree_sorts
     * @Fields treeSorts 所有级别排序号
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "所有级别排序号")
    private String treeSorts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.tree_leaf
     * @Fields treeLeaf 是否最末级
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "是否最末级")
    private String treeLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.tree_level
     * @Fields treeLevel 层次级别
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "层次级别")
    private Short treeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.tree_names
     * @Fields treeNames 全节点名
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "全节点名")
    private String treeNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.view_code
     * @Fields viewCode 公司代码
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "公司代码")
    private String viewCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.company_name
     * @Fields companyName 公司名称
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "公司名称")
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.full_name
     * @Fields fullName 公司全称
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "公司全称")
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.area_code
     * @Fields areaCode 区域编码
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "区域编码")
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.status
     * @Fields status 状态（0正常 1删除 2停用）
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "状态（0正常 1删除 2停用）")
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.create_by
     * @Fields createBy 创建者
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "创建者")
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.update_by
     * @Fields updateBy 更新者
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "更新者")
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.remarks
     * @Fields remarks 备注信息
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "备注信息")
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.corp_code
     * @Fields corpCode 租户代码
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "租户代码")
    private String corpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.corp_name
     * @Fields corpName 租户名称
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "租户名称")
    private String corpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_s1
     * @Fields extendS1 扩展 String 1
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 String 1")
    private String extendS1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_s2
     * @Fields extendS2 扩展 String 2
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 String 2")
    private String extendS2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_s3
     * @Fields extendS3 扩展 String 3
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 String 3")
    private String extendS3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_s4
     * @Fields extendS4 扩展 String 4
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 String 4")
    private String extendS4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_s5
     * @Fields extendS5 扩展 String 5
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 String 5")
    private String extendS5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_s6
     * @Fields extendS6 扩展 String 6
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 String 6")
    private String extendS6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_s7
     * @Fields extendS7 扩展 String 7
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 String 7")
    private String extendS7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_s8
     * @Fields extendS8 扩展 String 8
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 String 8")
    private String extendS8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_i1
     * @Fields extendI1 扩展 Integer 1
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Integer 1")
    private BigDecimal extendI1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_i2
     * @Fields extendI2 扩展 Integer 2
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Integer 2")
    private BigDecimal extendI2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_i3
     * @Fields extendI3 扩展 Integer 3
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Integer 3")
    private BigDecimal extendI3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_i4
     * @Fields extendI4 扩展 Integer 4
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Integer 4")
    private BigDecimal extendI4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_f1
     * @Fields extendF1 扩展 Float 1
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Float 1")
    private BigDecimal extendF1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_f2
     * @Fields extendF2 扩展 Float 2
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Float 2")
    private BigDecimal extendF2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_f3
     * @Fields extendF3 扩展 Float 3
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Float 3")
    private BigDecimal extendF3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_f4
     * @Fields extendF4 扩展 Float 4
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Float 4")
    private BigDecimal extendF4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_d1
     * @Fields extendD1 扩展 Date 1
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Date 1")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date extendD1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_d2
     * @Fields extendD2 扩展 Date 2
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Date 2")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date extendD2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_d3
     * @Fields extendD3 扩展 Date 3
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Date 3")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date extendD3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.extend_d4
     * @Fields extendD4 扩展 Date 4
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "扩展 Date 4")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date extendD4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_company
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 公司编码 字段:sys_company.company_code
     *
     * @return sys_company.company_code, 公司编码
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * 设置 公司编码 字段:sys_company.company_code
     *
     * @param companyCode the value for sys_company.company_code, 公司编码
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * 获取 父级编号 字段:sys_company.parent_code
     *
     * @return sys_company.parent_code, 父级编号
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * 设置 父级编号 字段:sys_company.parent_code
     *
     * @param parentCode the value for sys_company.parent_code, 父级编号
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * 获取 所有父级编号 字段:sys_company.parent_codes
     *
     * @return sys_company.parent_codes, 所有父级编号
     */
    public String getParentCodes() {
        return parentCodes;
    }

    /**
     * 设置 所有父级编号 字段:sys_company.parent_codes
     *
     * @param parentCodes the value for sys_company.parent_codes, 所有父级编号
     */
    public void setParentCodes(String parentCodes) {
        this.parentCodes = parentCodes == null ? null : parentCodes.trim();
    }

    /**
     * 获取 本级排序号（升序） 字段:sys_company.tree_sort
     *
     * @return sys_company.tree_sort, 本级排序号（升序）
     */
    public Long getTreeSort() {
        return treeSort;
    }

    /**
     * 设置 本级排序号（升序） 字段:sys_company.tree_sort
     *
     * @param treeSort the value for sys_company.tree_sort, 本级排序号（升序）
     */
    public void setTreeSort(Long treeSort) {
        this.treeSort = treeSort;
    }

    /**
     * 获取 所有级别排序号 字段:sys_company.tree_sorts
     *
     * @return sys_company.tree_sorts, 所有级别排序号
     */
    public String getTreeSorts() {
        return treeSorts;
    }

    /**
     * 设置 所有级别排序号 字段:sys_company.tree_sorts
     *
     * @param treeSorts the value for sys_company.tree_sorts, 所有级别排序号
     */
    public void setTreeSorts(String treeSorts) {
        this.treeSorts = treeSorts == null ? null : treeSorts.trim();
    }

    /**
     * 获取 是否最末级 字段:sys_company.tree_leaf
     *
     * @return sys_company.tree_leaf, 是否最末级
     */
    public String getTreeLeaf() {
        return treeLeaf;
    }

    /**
     * 设置 是否最末级 字段:sys_company.tree_leaf
     *
     * @param treeLeaf the value for sys_company.tree_leaf, 是否最末级
     */
    public void setTreeLeaf(String treeLeaf) {
        this.treeLeaf = treeLeaf == null ? null : treeLeaf.trim();
    }

    /**
     * 获取 层次级别 字段:sys_company.tree_level
     *
     * @return sys_company.tree_level, 层次级别
     */
    public Short getTreeLevel() {
        return treeLevel;
    }

    /**
     * 设置 层次级别 字段:sys_company.tree_level
     *
     * @param treeLevel the value for sys_company.tree_level, 层次级别
     */
    public void setTreeLevel(Short treeLevel) {
        this.treeLevel = treeLevel;
    }

    /**
     * 获取 全节点名 字段:sys_company.tree_names
     *
     * @return sys_company.tree_names, 全节点名
     */
    public String getTreeNames() {
        return treeNames;
    }

    /**
     * 设置 全节点名 字段:sys_company.tree_names
     *
     * @param treeNames the value for sys_company.tree_names, 全节点名
     */
    public void setTreeNames(String treeNames) {
        this.treeNames = treeNames == null ? null : treeNames.trim();
    }

    /**
     * 获取 公司代码 字段:sys_company.view_code
     *
     * @return sys_company.view_code, 公司代码
     */
    public String getViewCode() {
        return viewCode;
    }

    /**
     * 设置 公司代码 字段:sys_company.view_code
     *
     * @param viewCode the value for sys_company.view_code, 公司代码
     */
    public void setViewCode(String viewCode) {
        this.viewCode = viewCode == null ? null : viewCode.trim();
    }

    /**
     * 获取 公司名称 字段:sys_company.company_name
     *
     * @return sys_company.company_name, 公司名称
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * 设置 公司名称 字段:sys_company.company_name
     *
     * @param companyName the value for sys_company.company_name, 公司名称
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * 获取 公司全称 字段:sys_company.full_name
     *
     * @return sys_company.full_name, 公司全称
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * 设置 公司全称 字段:sys_company.full_name
     *
     * @param fullName the value for sys_company.full_name, 公司全称
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * 获取 区域编码 字段:sys_company.area_code
     *
     * @return sys_company.area_code, 区域编码
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * 设置 区域编码 字段:sys_company.area_code
     *
     * @param areaCode the value for sys_company.area_code, 区域编码
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * 获取 状态（0正常 1删除 2停用） 字段:sys_company.status
     *
     * @return sys_company.status, 状态（0正常 1删除 2停用）
     */
    public String getStatus() {
        return status;
    }

    /**
     * 设置 状态（0正常 1删除 2停用） 字段:sys_company.status
     *
     * @param status the value for sys_company.status, 状态（0正常 1删除 2停用）
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 获取 创建者 字段:sys_company.create_by
     *
     * @return sys_company.create_by, 创建者
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * 设置 创建者 字段:sys_company.create_by
     *
     * @param createBy the value for sys_company.create_by, 创建者
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * 获取 更新者 字段:sys_company.update_by
     *
     * @return sys_company.update_by, 更新者
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * 设置 更新者 字段:sys_company.update_by
     *
     * @param updateBy the value for sys_company.update_by, 更新者
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * 获取 备注信息 字段:sys_company.remarks
     *
     * @return sys_company.remarks, 备注信息
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * 设置 备注信息 字段:sys_company.remarks
     *
     * @param remarks the value for sys_company.remarks, 备注信息
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * 获取 租户代码 字段:sys_company.corp_code
     *
     * @return sys_company.corp_code, 租户代码
     */
    public String getCorpCode() {
        return corpCode;
    }

    /**
     * 设置 租户代码 字段:sys_company.corp_code
     *
     * @param corpCode the value for sys_company.corp_code, 租户代码
     */
    public void setCorpCode(String corpCode) {
        this.corpCode = corpCode == null ? null : corpCode.trim();
    }

    /**
     * 获取 租户名称 字段:sys_company.corp_name
     *
     * @return sys_company.corp_name, 租户名称
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * 设置 租户名称 字段:sys_company.corp_name
     *
     * @param corpName the value for sys_company.corp_name, 租户名称
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * 获取 扩展 String 1 字段:sys_company.extend_s1
     *
     * @return sys_company.extend_s1, 扩展 String 1
     */
    public String getExtendS1() {
        return extendS1;
    }

    /**
     * 设置 扩展 String 1 字段:sys_company.extend_s1
     *
     * @param extendS1 the value for sys_company.extend_s1, 扩展 String 1
     */
    public void setExtendS1(String extendS1) {
        this.extendS1 = extendS1 == null ? null : extendS1.trim();
    }

    /**
     * 获取 扩展 String 2 字段:sys_company.extend_s2
     *
     * @return sys_company.extend_s2, 扩展 String 2
     */
    public String getExtendS2() {
        return extendS2;
    }

    /**
     * 设置 扩展 String 2 字段:sys_company.extend_s2
     *
     * @param extendS2 the value for sys_company.extend_s2, 扩展 String 2
     */
    public void setExtendS2(String extendS2) {
        this.extendS2 = extendS2 == null ? null : extendS2.trim();
    }

    /**
     * 获取 扩展 String 3 字段:sys_company.extend_s3
     *
     * @return sys_company.extend_s3, 扩展 String 3
     */
    public String getExtendS3() {
        return extendS3;
    }

    /**
     * 设置 扩展 String 3 字段:sys_company.extend_s3
     *
     * @param extendS3 the value for sys_company.extend_s3, 扩展 String 3
     */
    public void setExtendS3(String extendS3) {
        this.extendS3 = extendS3 == null ? null : extendS3.trim();
    }

    /**
     * 获取 扩展 String 4 字段:sys_company.extend_s4
     *
     * @return sys_company.extend_s4, 扩展 String 4
     */
    public String getExtendS4() {
        return extendS4;
    }

    /**
     * 设置 扩展 String 4 字段:sys_company.extend_s4
     *
     * @param extendS4 the value for sys_company.extend_s4, 扩展 String 4
     */
    public void setExtendS4(String extendS4) {
        this.extendS4 = extendS4 == null ? null : extendS4.trim();
    }

    /**
     * 获取 扩展 String 5 字段:sys_company.extend_s5
     *
     * @return sys_company.extend_s5, 扩展 String 5
     */
    public String getExtendS5() {
        return extendS5;
    }

    /**
     * 设置 扩展 String 5 字段:sys_company.extend_s5
     *
     * @param extendS5 the value for sys_company.extend_s5, 扩展 String 5
     */
    public void setExtendS5(String extendS5) {
        this.extendS5 = extendS5 == null ? null : extendS5.trim();
    }

    /**
     * 获取 扩展 String 6 字段:sys_company.extend_s6
     *
     * @return sys_company.extend_s6, 扩展 String 6
     */
    public String getExtendS6() {
        return extendS6;
    }

    /**
     * 设置 扩展 String 6 字段:sys_company.extend_s6
     *
     * @param extendS6 the value for sys_company.extend_s6, 扩展 String 6
     */
    public void setExtendS6(String extendS6) {
        this.extendS6 = extendS6 == null ? null : extendS6.trim();
    }

    /**
     * 获取 扩展 String 7 字段:sys_company.extend_s7
     *
     * @return sys_company.extend_s7, 扩展 String 7
     */
    public String getExtendS7() {
        return extendS7;
    }

    /**
     * 设置 扩展 String 7 字段:sys_company.extend_s7
     *
     * @param extendS7 the value for sys_company.extend_s7, 扩展 String 7
     */
    public void setExtendS7(String extendS7) {
        this.extendS7 = extendS7 == null ? null : extendS7.trim();
    }

    /**
     * 获取 扩展 String 8 字段:sys_company.extend_s8
     *
     * @return sys_company.extend_s8, 扩展 String 8
     */
    public String getExtendS8() {
        return extendS8;
    }

    /**
     * 设置 扩展 String 8 字段:sys_company.extend_s8
     *
     * @param extendS8 the value for sys_company.extend_s8, 扩展 String 8
     */
    public void setExtendS8(String extendS8) {
        this.extendS8 = extendS8 == null ? null : extendS8.trim();
    }

    /**
     * 获取 扩展 Integer 1 字段:sys_company.extend_i1
     *
     * @return sys_company.extend_i1, 扩展 Integer 1
     */
    public BigDecimal getExtendI1() {
        return extendI1;
    }

    /**
     * 设置 扩展 Integer 1 字段:sys_company.extend_i1
     *
     * @param extendI1 the value for sys_company.extend_i1, 扩展 Integer 1
     */
    public void setExtendI1(BigDecimal extendI1) {
        this.extendI1 = extendI1;
    }

    /**
     * 获取 扩展 Integer 2 字段:sys_company.extend_i2
     *
     * @return sys_company.extend_i2, 扩展 Integer 2
     */
    public BigDecimal getExtendI2() {
        return extendI2;
    }

    /**
     * 设置 扩展 Integer 2 字段:sys_company.extend_i2
     *
     * @param extendI2 the value for sys_company.extend_i2, 扩展 Integer 2
     */
    public void setExtendI2(BigDecimal extendI2) {
        this.extendI2 = extendI2;
    }

    /**
     * 获取 扩展 Integer 3 字段:sys_company.extend_i3
     *
     * @return sys_company.extend_i3, 扩展 Integer 3
     */
    public BigDecimal getExtendI3() {
        return extendI3;
    }

    /**
     * 设置 扩展 Integer 3 字段:sys_company.extend_i3
     *
     * @param extendI3 the value for sys_company.extend_i3, 扩展 Integer 3
     */
    public void setExtendI3(BigDecimal extendI3) {
        this.extendI3 = extendI3;
    }

    /**
     * 获取 扩展 Integer 4 字段:sys_company.extend_i4
     *
     * @return sys_company.extend_i4, 扩展 Integer 4
     */
    public BigDecimal getExtendI4() {
        return extendI4;
    }

    /**
     * 设置 扩展 Integer 4 字段:sys_company.extend_i4
     *
     * @param extendI4 the value for sys_company.extend_i4, 扩展 Integer 4
     */
    public void setExtendI4(BigDecimal extendI4) {
        this.extendI4 = extendI4;
    }

    /**
     * 获取 扩展 Float 1 字段:sys_company.extend_f1
     *
     * @return sys_company.extend_f1, 扩展 Float 1
     */
    public BigDecimal getExtendF1() {
        return extendF1;
    }

    /**
     * 设置 扩展 Float 1 字段:sys_company.extend_f1
     *
     * @param extendF1 the value for sys_company.extend_f1, 扩展 Float 1
     */
    public void setExtendF1(BigDecimal extendF1) {
        this.extendF1 = extendF1;
    }

    /**
     * 获取 扩展 Float 2 字段:sys_company.extend_f2
     *
     * @return sys_company.extend_f2, 扩展 Float 2
     */
    public BigDecimal getExtendF2() {
        return extendF2;
    }

    /**
     * 设置 扩展 Float 2 字段:sys_company.extend_f2
     *
     * @param extendF2 the value for sys_company.extend_f2, 扩展 Float 2
     */
    public void setExtendF2(BigDecimal extendF2) {
        this.extendF2 = extendF2;
    }

    /**
     * 获取 扩展 Float 3 字段:sys_company.extend_f3
     *
     * @return sys_company.extend_f3, 扩展 Float 3
     */
    public BigDecimal getExtendF3() {
        return extendF3;
    }

    /**
     * 设置 扩展 Float 3 字段:sys_company.extend_f3
     *
     * @param extendF3 the value for sys_company.extend_f3, 扩展 Float 3
     */
    public void setExtendF3(BigDecimal extendF3) {
        this.extendF3 = extendF3;
    }

    /**
     * 获取 扩展 Float 4 字段:sys_company.extend_f4
     *
     * @return sys_company.extend_f4, 扩展 Float 4
     */
    public BigDecimal getExtendF4() {
        return extendF4;
    }

    /**
     * 设置 扩展 Float 4 字段:sys_company.extend_f4
     *
     * @param extendF4 the value for sys_company.extend_f4, 扩展 Float 4
     */
    public void setExtendF4(BigDecimal extendF4) {
        this.extendF4 = extendF4;
    }

    /**
     * 获取 扩展 Date 1 字段:sys_company.extend_d1
     *
     * @return sys_company.extend_d1, 扩展 Date 1
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getExtendD1() {
        return extendD1;
    }

    /**
     * 设置 扩展 Date 1 字段:sys_company.extend_d1
     *
     * @param extendD1 the value for sys_company.extend_d1, 扩展 Date 1
     */
    public void setExtendD1(Date extendD1) {
        this.extendD1 = extendD1;
    }

    /**
     * 获取 扩展 Date 2 字段:sys_company.extend_d2
     *
     * @return sys_company.extend_d2, 扩展 Date 2
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getExtendD2() {
        return extendD2;
    }

    /**
     * 设置 扩展 Date 2 字段:sys_company.extend_d2
     *
     * @param extendD2 the value for sys_company.extend_d2, 扩展 Date 2
     */
    public void setExtendD2(Date extendD2) {
        this.extendD2 = extendD2;
    }

    /**
     * 获取 扩展 Date 3 字段:sys_company.extend_d3
     *
     * @return sys_company.extend_d3, 扩展 Date 3
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getExtendD3() {
        return extendD3;
    }

    /**
     * 设置 扩展 Date 3 字段:sys_company.extend_d3
     *
     * @param extendD3 the value for sys_company.extend_d3, 扩展 Date 3
     */
    public void setExtendD3(Date extendD3) {
        this.extendD3 = extendD3;
    }

    /**
     * 获取 扩展 Date 4 字段:sys_company.extend_d4
     *
     * @return sys_company.extend_d4, 扩展 Date 4
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getExtendD4() {
        return extendD4;
    }

    /**
     * 设置 扩展 Date 4 字段:sys_company.extend_d4
     *
     * @param extendD4 the value for sys_company.extend_d4, 扩展 Date 4
     */
    public void setExtendD4(Date extendD4) {
        this.extendD4 = extendD4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company 公司表  
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", companyCode=").append(companyCode);
        sb.append(", parentCode=").append(parentCode);
        sb.append(", parentCodes=").append(parentCodes);
        sb.append(", treeSort=").append(treeSort);
        sb.append(", treeSorts=").append(treeSorts);
        sb.append(", treeLeaf=").append(treeLeaf);
        sb.append(", treeLevel=").append(treeLevel);
        sb.append(", treeNames=").append(treeNames);
        sb.append(", viewCode=").append(viewCode);
        sb.append(", companyName=").append(companyName);
        sb.append(", fullName=").append(fullName);
        sb.append(", areaCode=").append(areaCode);
        sb.append(", status=").append(status);
        sb.append(", createBy=").append(createBy);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", remarks=").append(remarks);
        sb.append(", corpCode=").append(corpCode);
        sb.append(", corpName=").append(corpName);
        sb.append(", extendS1=").append(extendS1);
        sb.append(", extendS2=").append(extendS2);
        sb.append(", extendS3=").append(extendS3);
        sb.append(", extendS4=").append(extendS4);
        sb.append(", extendS5=").append(extendS5);
        sb.append(", extendS6=").append(extendS6);
        sb.append(", extendS7=").append(extendS7);
        sb.append(", extendS8=").append(extendS8);
        sb.append(", extendI1=").append(extendI1);
        sb.append(", extendI2=").append(extendI2);
        sb.append(", extendI3=").append(extendI3);
        sb.append(", extendI4=").append(extendI4);
        sb.append(", extendF1=").append(extendF1);
        sb.append(", extendF2=").append(extendF2);
        sb.append(", extendF3=").append(extendF3);
        sb.append(", extendF4=").append(extendF4);
        sb.append(", extendD1=").append(extendD1);
        sb.append(", extendD2=").append(extendD2);
        sb.append(", extendD3=").append(extendD3);
        sb.append(", extendD4=").append(extendD4);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company 公司表  
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Company other = (Company) that;
        return (this.getCompanyCode() == null ? other.getCompanyCode() == null : this.getCompanyCode().equals(other.getCompanyCode()))
            && (this.getParentCode() == null ? other.getParentCode() == null : this.getParentCode().equals(other.getParentCode()))
            && (this.getParentCodes() == null ? other.getParentCodes() == null : this.getParentCodes().equals(other.getParentCodes()))
            && (this.getTreeSort() == null ? other.getTreeSort() == null : this.getTreeSort().equals(other.getTreeSort()))
            && (this.getTreeSorts() == null ? other.getTreeSorts() == null : this.getTreeSorts().equals(other.getTreeSorts()))
            && (this.getTreeLeaf() == null ? other.getTreeLeaf() == null : this.getTreeLeaf().equals(other.getTreeLeaf()))
            && (this.getTreeLevel() == null ? other.getTreeLevel() == null : this.getTreeLevel().equals(other.getTreeLevel()))
            && (this.getTreeNames() == null ? other.getTreeNames() == null : this.getTreeNames().equals(other.getTreeNames()))
            && (this.getViewCode() == null ? other.getViewCode() == null : this.getViewCode().equals(other.getViewCode()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getFullName() == null ? other.getFullName() == null : this.getFullName().equals(other.getFullName()))
            && (this.getAreaCode() == null ? other.getAreaCode() == null : this.getAreaCode().equals(other.getAreaCode()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getCorpCode() == null ? other.getCorpCode() == null : this.getCorpCode().equals(other.getCorpCode()))
            && (this.getCorpName() == null ? other.getCorpName() == null : this.getCorpName().equals(other.getCorpName()))
            && (this.getExtendS1() == null ? other.getExtendS1() == null : this.getExtendS1().equals(other.getExtendS1()))
            && (this.getExtendS2() == null ? other.getExtendS2() == null : this.getExtendS2().equals(other.getExtendS2()))
            && (this.getExtendS3() == null ? other.getExtendS3() == null : this.getExtendS3().equals(other.getExtendS3()))
            && (this.getExtendS4() == null ? other.getExtendS4() == null : this.getExtendS4().equals(other.getExtendS4()))
            && (this.getExtendS5() == null ? other.getExtendS5() == null : this.getExtendS5().equals(other.getExtendS5()))
            && (this.getExtendS6() == null ? other.getExtendS6() == null : this.getExtendS6().equals(other.getExtendS6()))
            && (this.getExtendS7() == null ? other.getExtendS7() == null : this.getExtendS7().equals(other.getExtendS7()))
            && (this.getExtendS8() == null ? other.getExtendS8() == null : this.getExtendS8().equals(other.getExtendS8()))
            && (this.getExtendI1() == null ? other.getExtendI1() == null : this.getExtendI1().equals(other.getExtendI1()))
            && (this.getExtendI2() == null ? other.getExtendI2() == null : this.getExtendI2().equals(other.getExtendI2()))
            && (this.getExtendI3() == null ? other.getExtendI3() == null : this.getExtendI3().equals(other.getExtendI3()))
            && (this.getExtendI4() == null ? other.getExtendI4() == null : this.getExtendI4().equals(other.getExtendI4()))
            && (this.getExtendF1() == null ? other.getExtendF1() == null : this.getExtendF1().equals(other.getExtendF1()))
            && (this.getExtendF2() == null ? other.getExtendF2() == null : this.getExtendF2().equals(other.getExtendF2()))
            && (this.getExtendF3() == null ? other.getExtendF3() == null : this.getExtendF3().equals(other.getExtendF3()))
            && (this.getExtendF4() == null ? other.getExtendF4() == null : this.getExtendF4().equals(other.getExtendF4()))
            && (this.getExtendD1() == null ? other.getExtendD1() == null : this.getExtendD1().equals(other.getExtendD1()))
            && (this.getExtendD2() == null ? other.getExtendD2() == null : this.getExtendD2().equals(other.getExtendD2()))
            && (this.getExtendD3() == null ? other.getExtendD3() == null : this.getExtendD3().equals(other.getExtendD3()))
            && (this.getExtendD4() == null ? other.getExtendD4() == null : this.getExtendD4().equals(other.getExtendD4()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company 公司表  
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCompanyCode() == null) ? 0 : getCompanyCode().hashCode());
        result = prime * result + ((getParentCode() == null) ? 0 : getParentCode().hashCode());
        result = prime * result + ((getParentCodes() == null) ? 0 : getParentCodes().hashCode());
        result = prime * result + ((getTreeSort() == null) ? 0 : getTreeSort().hashCode());
        result = prime * result + ((getTreeSorts() == null) ? 0 : getTreeSorts().hashCode());
        result = prime * result + ((getTreeLeaf() == null) ? 0 : getTreeLeaf().hashCode());
        result = prime * result + ((getTreeLevel() == null) ? 0 : getTreeLevel().hashCode());
        result = prime * result + ((getTreeNames() == null) ? 0 : getTreeNames().hashCode());
        result = prime * result + ((getViewCode() == null) ? 0 : getViewCode().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getFullName() == null) ? 0 : getFullName().hashCode());
        result = prime * result + ((getAreaCode() == null) ? 0 : getAreaCode().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getCorpCode() == null) ? 0 : getCorpCode().hashCode());
        result = prime * result + ((getCorpName() == null) ? 0 : getCorpName().hashCode());
        result = prime * result + ((getExtendS1() == null) ? 0 : getExtendS1().hashCode());
        result = prime * result + ((getExtendS2() == null) ? 0 : getExtendS2().hashCode());
        result = prime * result + ((getExtendS3() == null) ? 0 : getExtendS3().hashCode());
        result = prime * result + ((getExtendS4() == null) ? 0 : getExtendS4().hashCode());
        result = prime * result + ((getExtendS5() == null) ? 0 : getExtendS5().hashCode());
        result = prime * result + ((getExtendS6() == null) ? 0 : getExtendS6().hashCode());
        result = prime * result + ((getExtendS7() == null) ? 0 : getExtendS7().hashCode());
        result = prime * result + ((getExtendS8() == null) ? 0 : getExtendS8().hashCode());
        result = prime * result + ((getExtendI1() == null) ? 0 : getExtendI1().hashCode());
        result = prime * result + ((getExtendI2() == null) ? 0 : getExtendI2().hashCode());
        result = prime * result + ((getExtendI3() == null) ? 0 : getExtendI3().hashCode());
        result = prime * result + ((getExtendI4() == null) ? 0 : getExtendI4().hashCode());
        result = prime * result + ((getExtendF1() == null) ? 0 : getExtendF1().hashCode());
        result = prime * result + ((getExtendF2() == null) ? 0 : getExtendF2().hashCode());
        result = prime * result + ((getExtendF3() == null) ? 0 : getExtendF3().hashCode());
        result = prime * result + ((getExtendF4() == null) ? 0 : getExtendF4().hashCode());
        result = prime * result + ((getExtendD1() == null) ? 0 : getExtendD1().hashCode());
        result = prime * result + ((getExtendD2() == null) ? 0 : getExtendD2().hashCode());
        result = prime * result + ((getExtendD3() == null) ? 0 : getExtendD3().hashCode());
        result = prime * result + ((getExtendD4() == null) ? 0 : getExtendD4().hashCode());
        return result;
    }
}