/*
* Module.java
* @author ICL
* @date 2018-10-31 23:29:21
*/
package com.hwitec.core.domain;

import java.io.Serializable;
import org.common.domain.DataEntity;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_module
 *
 * @mbg.generated 2018-10-31 23:29:21
 */
import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 模块表
 * 实体类对应的数据表为:sys_module
 * @author ICL
 * @date 2018-10-31 23:29:21
 */
@ApiModel(value ="Module")
public class Module extends DataEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.module_code
     * @Fields moduleCode 模块编码
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "模块编码")
    private String moduleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.module_name
     * @Fields moduleName 模块名称
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "模块名称")
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.description
     * @Fields description 模块描述
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "模块描述")
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.main_class_name
     * @Fields mainClassName 主类全名
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "主类全名")
    private String mainClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.current_version
     * @Fields currentVersion 当前版本
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "当前版本")
    private String currentVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.upgrade_info
     * @Fields upgradeInfo 升级信息
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "升级信息")
    private String upgradeInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.status
     * @Fields status 状态（0正常 1删除 2停用）
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "状态（0正常 1删除 2停用）")
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.create_by
     * @Fields createBy 创建者
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "创建者")
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.update_by
     * @Fields updateBy 更新者
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "更新者")
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.remarks
     * @Fields remarks 备注信息
     *
     * @mbg.generated 2018-10-31 23:29:21
     **/
    @ApiModelProperty(value = "备注信息")
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_module
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 模块编码 字段:sys_module.module_code
     *
     * @return sys_module.module_code, 模块编码
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * 设置 模块编码 字段:sys_module.module_code
     *
     * @param moduleCode the value for sys_module.module_code, 模块编码
     */
    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode == null ? null : moduleCode.trim();
    }

    /**
     * 获取 模块名称 字段:sys_module.module_name
     *
     * @return sys_module.module_name, 模块名称
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * 设置 模块名称 字段:sys_module.module_name
     *
     * @param moduleName the value for sys_module.module_name, 模块名称
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * 获取 模块描述 字段:sys_module.description
     *
     * @return sys_module.description, 模块描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置 模块描述 字段:sys_module.description
     *
     * @param description the value for sys_module.description, 模块描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取 主类全名 字段:sys_module.main_class_name
     *
     * @return sys_module.main_class_name, 主类全名
     */
    public String getMainClassName() {
        return mainClassName;
    }

    /**
     * 设置 主类全名 字段:sys_module.main_class_name
     *
     * @param mainClassName the value for sys_module.main_class_name, 主类全名
     */
    public void setMainClassName(String mainClassName) {
        this.mainClassName = mainClassName == null ? null : mainClassName.trim();
    }

    /**
     * 获取 当前版本 字段:sys_module.current_version
     *
     * @return sys_module.current_version, 当前版本
     */
    public String getCurrentVersion() {
        return currentVersion;
    }

    /**
     * 设置 当前版本 字段:sys_module.current_version
     *
     * @param currentVersion the value for sys_module.current_version, 当前版本
     */
    public void setCurrentVersion(String currentVersion) {
        this.currentVersion = currentVersion == null ? null : currentVersion.trim();
    }

    /**
     * 获取 升级信息 字段:sys_module.upgrade_info
     *
     * @return sys_module.upgrade_info, 升级信息
     */
    public String getUpgradeInfo() {
        return upgradeInfo;
    }

    /**
     * 设置 升级信息 字段:sys_module.upgrade_info
     *
     * @param upgradeInfo the value for sys_module.upgrade_info, 升级信息
     */
    public void setUpgradeInfo(String upgradeInfo) {
        this.upgradeInfo = upgradeInfo == null ? null : upgradeInfo.trim();
    }

    /**
     * 获取 状态（0正常 1删除 2停用） 字段:sys_module.status
     *
     * @return sys_module.status, 状态（0正常 1删除 2停用）
     */
    public String getStatus() {
        return status;
    }

    /**
     * 设置 状态（0正常 1删除 2停用） 字段:sys_module.status
     *
     * @param status the value for sys_module.status, 状态（0正常 1删除 2停用）
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 获取 创建者 字段:sys_module.create_by
     *
     * @return sys_module.create_by, 创建者
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * 设置 创建者 字段:sys_module.create_by
     *
     * @param createBy the value for sys_module.create_by, 创建者
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * 获取 更新者 字段:sys_module.update_by
     *
     * @return sys_module.update_by, 更新者
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * 设置 更新者 字段:sys_module.update_by
     *
     * @param updateBy the value for sys_module.update_by, 更新者
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * 获取 备注信息 字段:sys_module.remarks
     *
     * @return sys_module.remarks, 备注信息
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * 设置 备注信息 字段:sys_module.remarks
     *
     * @param remarks the value for sys_module.remarks, 备注信息
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module 模块表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", moduleCode=").append(moduleCode);
        sb.append(", moduleName=").append(moduleName);
        sb.append(", description=").append(description);
        sb.append(", mainClassName=").append(mainClassName);
        sb.append(", currentVersion=").append(currentVersion);
        sb.append(", upgradeInfo=").append(upgradeInfo);
        sb.append(", status=").append(status);
        sb.append(", createBy=").append(createBy);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", remarks=").append(remarks);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module 模块表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Module other = (Module) that;
        return (this.getModuleCode() == null ? other.getModuleCode() == null : this.getModuleCode().equals(other.getModuleCode()))
            && (this.getModuleName() == null ? other.getModuleName() == null : this.getModuleName().equals(other.getModuleName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getMainClassName() == null ? other.getMainClassName() == null : this.getMainClassName().equals(other.getMainClassName()))
            && (this.getCurrentVersion() == null ? other.getCurrentVersion() == null : this.getCurrentVersion().equals(other.getCurrentVersion()))
            && (this.getUpgradeInfo() == null ? other.getUpgradeInfo() == null : this.getUpgradeInfo().equals(other.getUpgradeInfo()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module 模块表
     *
     * @mbg.generated 2018-10-31 23:29:21
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getModuleCode() == null) ? 0 : getModuleCode().hashCode());
        result = prime * result + ((getModuleName() == null) ? 0 : getModuleName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getMainClassName() == null) ? 0 : getMainClassName().hashCode());
        result = prime * result + ((getCurrentVersion() == null) ? 0 : getCurrentVersion().hashCode());
        result = prime * result + ((getUpgradeInfo() == null) ? 0 : getUpgradeInfo().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        return result;
    }
}